name: Playwright Tests with Allure

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      # Use your custom Docker image with Playwright + Java
      image: lini007/playwright-java:latest
      options: --ipc=host

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI globally
        run: npm install -g allure-commandline --save-dev

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test

      - name: Generate Allure report
        run: allure generate ./allure-results -o ./allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
